CREATE TABLE tbl_item_pizza_mes(
idItemPagina INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
titulo VARCHAR(120) NOT NULL,
descricao VARCHAR(240) NOT NULL,
preco DECIMAL(5,2) NOT NULL,
imagem VARCHAR(340) NOT NULL,
ativo TINYINT(1) NOT NULL);